spring:
  application:
    name: URLShortener
  datasource:
    url: jdbc:postgresql://localhost:5433/urlShortener
    username: postgres
    password: Abhuday@2003
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    port: 6379
    host: localhost
server:
  port: 8080
